/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.watermedia.androidbridge;

/**
 * Immutable view of a parsed {@code /watermedia_android/payload.cfg} manifest.
 * The manifest is generated by {@code tools/pack-payload.ps1} from the real
 * files, so the sizes can be used to verify an extraction.
 */
public final class VlcPayload {
    public final String payloadVersion;
    public final String vlcVersion;
    public final String vlcSource;
    public final String jnaVersion;

    /** Relative path ({@code <abi>/<file name>}) to expected byte size for libvlc payload files. */
    public final java.util.Map<String, Long> natives = new java.util.LinkedHashMap<>();
    /** Relative path to expected byte size for bundled JNA dispatch libraries. */
    public final java.util.Map<String, Long> jna = new java.util.LinkedHashMap<>();

    VlcPayload(final String payloadVersion, final String vlcVersion, final String vlcSource, final String jnaVersion) {
        this.payloadVersion = payloadVersion;
        this.vlcVersion = vlcVersion;
        this.vlcSource = vlcSource;
        this.jnaVersion = jnaVersion;
    }

    public void add(final String kind, final String relativePath, final long size) {
        if ("jna".equals(kind)) {
            this.jna.put(relativePath, size);
        } else {
            this.natives.put(relativePath, size);
        }
    }

    /** Files of the given ABI, as file names only. */
    public java.util.List<String> filesFor(final java.util.Map<String, Long> source, final String abi) {
        final java.util.List<String> result = new java.util.ArrayList<>();
        final String prefix = abi + '/';
        for (final String key : source.keySet()) {
            if (key.startsWith(prefix)) result.add(key.substring(prefix.length()));
        }
        java.util.Collections.sort(result);
        return result;
    }

    public boolean knowsAbi(final String abi) {
        return !filesFor(this.natives, abi).isEmpty();
    }

    public java.util.List<String> abis() {
        final java.util.TreeSet<String> result = new java.util.TreeSet<>();
        for (final String key : this.natives.keySet()) {
            final int slash = key.indexOf('/');
            if (slash > 0) result.add(key.substring(0, slash));
        }
        return new java.util.ArrayList<>(result);
    }

    @Override
    public String toString() {
        return "VlcPayload{version=" + this.payloadVersion + ", vlc=" + this.vlcVersion
                + ", jna=" + this.jnaVersion + ", abis=" + this.abis() + '}';
    }
}
