# SPDX-License-Identifier: GPL-3.0-or-later
# Collects the VLC-for-Android native payload out of the official APKs and writes
# it into src/main/resources together with the manifest the installer verifies.
#
# The PojavLauncher JNA dispatch library is NOT bundled by default: the launchers
# that need it already provide a matching build, so shipping it would only add a
# third party binary that never activates (and another licence to honour).  Pass
# -IncludeJna to add it back; see META-INF/licenses/THIRD-PARTY-NOTICES.txt.
param([switch]$IncludeJna)

$ErrorActionPreference = 'Stop'
$root = 'D:\DSH\WATERMeDIA Android Bridge'
$apkDir = Join-Path $root 'vendor\downloads'
$jnaSrc = Join-Path $root 'vendor\jna'
$res = Join-Path $root 'src\main\resources\watermedia_android'
$tmp = Join-Path $root 'build\payload-tmp'

$vlcRelease = '3.7.1'
$payloadVersion = 'vlc3.0.23-android3.7.1-r2'
$abis = [ordered]@{
  'arm64-v8a'   = "VLC-Android-$vlcRelease-arm64-v8a.apk"
  'armeabi-v7a' = "VLC-Android-$vlcRelease-armeabi-v7a.apk"
  'x86_64'      = "VLC-Android-$vlcRelease-x86_64.apk"
}
# what libvlc.so needs at load time (see ELF DT_NEEDED); everything else is an
# Android system library and must not be bundled.
$nativeNames = @('libvlc.so', 'libc++_shared.so')

if (Test-Path $res) { Remove-Item $res -Recurse -Force }
New-Item -ItemType Directory -Force -Path "$res\natives" | Out-Null
if (Test-Path $tmp) { Remove-Item $tmp -Recurse -Force }

$manifest = New-Object System.Collections.Generic.List[string]
$manifest.Add('# GENERATED by tools/pack-payload.ps1 - do not edit by hand')
$manifest.Add("payloadVersion=$payloadVersion")
$manifest.Add('vlcVersion=3.0.23')
$manifest.Add("vlcSource=VLC-Android-$vlcRelease (https://get.videolan.org/vlc-android/$vlcRelease/)")

foreach ($abi in $abis.Keys) {
  $apk = Join-Path $apkDir $abis[$abi]
  if (-not (Test-Path $apk)) { throw "missing APK: $apk" }
  $stage = Join-Path $tmp $abi
  New-Item -ItemType Directory -Force -Path $stage | Out-Null
  foreach ($name in $nativeNames) {
    & tar -xf $apk -C $stage "lib/$abi/$name" 2>$null
    $file = Join-Path $stage "lib\$abi\$name"
    if (-not (Test-Path $file)) { throw "APK $($abis[$abi]) does not contain lib/$abi/$name" }
    $target = Join-Path "$res\natives\$abi" $name
    New-Item -ItemType Directory -Force -Path (Split-Path $target) | Out-Null
    Copy-Item $file $target -Force
    $size = (Get-Item $target).Length
    $manifest.Add("file=$abi/$name;$size;native")
    Write-Host ("[native] {0,-13} {1,-20} {2,12:N0} bytes" -f $abi, $name, $size)
  }
}

# Optional (opt-in): Android built JNA dispatch library, used as a fallback when a
# launcher provides none.  Not bundled by default - see the file header.
$jnaVersion = 'not-bundled'
if ($IncludeJna) {
  $jnaVersion = 'unknown'
  foreach ($abi in $abis.Keys) {
    $src = Join-Path $jnaSrc "libjnidispatch-$abi.so"
    if (-not (Test-Path $src)) { Write-Host "[jna   ] $abi - not available, skipping"; continue }
    if ((Get-Item $src).Length -lt 10000) { Write-Host "[jna   ] $abi - placeholder file, skipping"; continue }
    $target = Join-Path $res "jna\$abi\libjnidispatch.so"
    New-Item -ItemType Directory -Force -Path (Split-Path $target) | Out-Null
    Copy-Item $src $target -Force
    $size = (Get-Item $target).Length
    $manifest.Add("file=$abi/libjnidispatch.so;$size;jna")
    Write-Host ("[jna   ] {0,-13} libjnidispatch.so  {1,12:N0} bytes" -f $abi, $size)
    if ($jnaVersion -eq 'unknown') {
      $bytes = [System.IO.File]::ReadAllBytes($target)
      $cur = New-Object System.Text.StringBuilder
      $found = New-Object System.Collections.Generic.List[string]
      foreach ($b in $bytes) {
        if ($b -ge 32 -and $b -lt 127) { [void]$cur.Append([char]$b) }
        else { if ($cur.Length -ge 4) { [void]$found.Add($cur.ToString()) }; [void]$cur.Clear() }
      }
      $versions = @($found | Where-Object { $_ -match '^\d+\.\d+\.\d+$' } | Sort-Object -Unique)
      if ($versions -contains '5.14.0') { $jnaVersion = '5.14.0' }
      elseif ($versions.Count -gt 0) { $jnaVersion = [string]$versions[0] }
    }
  }
} else {
  Write-Host "[jna   ] not bundled (pass -IncludeJna to ship the PojavLauncher dispatch library)"
}
$manifest.Insert(4, "jnaVersion=$jnaVersion")

$manifestPath = Join-Path $res 'payload.cfg'
Set-Content -Path $manifestPath -Value $manifest -Encoding ASCII
Write-Host ""
Write-Host "payload manifest written to $manifestPath"
Get-Content $manifestPath
$total = (Get-ChildItem $res -Recurse -File | Measure-Object -Property Length -Sum).Sum
Write-Host ("payload total: {0:N1} MiB" -f ($total / 1MB))
